# https://golang.github.io/dep/docs/FAQ.html#how-do-i-use-dep-in-ci
language: go

go:
  - "1.16.x"

install: make all

before_deploy:
  - pip install --user awscli
  - make dist

deploy:
  skip_cleanup: true
  provider: script
  script: make publish
